<project name="MyInfArithProject" default="run" basedir=".">
    <property name="src.dir" value="src"/>
    <property name="build.dir" value="build"/>

    <target name="clean">
        <delete dir="${build.dir}"/>
    </target>

    <target name="compile">
        <mkdir dir="${build.dir}"/>
        <javac srcdir="${src.dir}" destdir="${build.dir}" includeantruntime="false"/>
    </target>

    <target name="run" depends="compile">
        <java classname="MyInfArith" classpath="${build.dir}" fork="true">
            <arg value="float"/>
            <arg value="div"/>
            <arg value="129029.29839"/>
            <arg value="129238"/>
        </java>
    </target>
</project>
